### PR TITLE
tock-responder: libtock-rs: Bump to the latest commit

### PR DESCRIPTION
**Pull request by alistair23**

### CODE REVIEW

**Comment by twilfredo** [comment]
for `nrf52840`, we need this change in libtock-rs https://github.com/twilfredo/libtock-rs/commit/924d277b6b332f9029cf33424e657b547b63c12d

Do you think we could upstream something like this for the above:

```
    #[cfg(feature = "default_layout")]
    ("nrf52840"           , "0x00040000", "768K"     , "0x20008000", "56K"    ),
    #[cfg(feature = "big_heap")]
    ("nrf52840"           , "0x00040000", "768K"     , "0x20010000", "128K"    ),
```

**Comment by alistair23** [comment]
The RAM size in libtock-rs should match the board. So if there is 128K of RAM we can update it in libtock-rs, no need for a `cfg` flag

**Comment by twilfredo** [comment]
> The RAM size in libtock-rs should match the board. So if there is 128K of RAM we can update it in libtock-rs, no need for a `cfg` flag

I thought this was the RAM size allocated for the app slice, so if we bump it to the max size then only 1 app can be loaded at a time. Is that wrong?

**Comment by alistair23** [comment]
That would depend on the board. If one app uses all the RAM then yes, you can only have one. But I don't think there is any point in artificially limiting application sizes. We can only run a single libtock-rs application anyway (without modifying addresses).

**Comment by twilfredo** [comment]
> That would depend on the board. If one app uses all the RAM then yes, you can only have one. But I don't think there is any point in artificially limiting application sizes. We can only run a single libtock-rs application anyway (without modifying addresses).

okay sounds good, I'll send a patch.

**Comment by twilfredo** [comment]
Do you wanna bump this commit to the latest latest master, it has the RNG api that just merged?

**Review by twilfredo — APPROVED** [review]

**Pull request merged**
