### PR TITLE
[RFC]: libspdm: add extern fn type checking

### PR DESCRIPTION
**Pull request by twilfredo**
@alistair23  I wanted to see if we could make the approach in https://github.com/westerndigitalcorporation/spdm-utils/pull/84 simpler. Same concept but simpler? I think. 

What do you think? When invoking the `libspdm_match_fn_prototypes!(type, name)`, just use the type we have locally, the macro should check that against the type generated binding which should catch any mismatches.

For example this outputs:

```
(rust:stable) ↪ cargo test
   Compiling SPDM-Utils v1.0.0 (/home/twilfred/wdc/spdm-utils)
error[E0308]: mismatched types
    --> src/libspdm/spdm.rs:1153:23
     |
1153 |           const _: $t = libspdm_rs::$name;
     |                         ^^^^^^^^^^^^^^^^^ incorrect number of function parameters
...
1158 | / libspdm_match_fn_prototypes!(
1159 | |     unsafe extern "C" fn(u8, *const c_void, usize) -> bool,
1160 | |     libspdm_write_certificate_to_nvm
1161 | | );
     | |_- in this macro invocation
     |
     = note: expected fn pointer `unsafe extern "C" fn(u8, *const c_void, usize) -> _`
                   found fn item `unsafe extern "C" fn(u8, *const c_void, usize, u32, u32) -> _ {libspdm_rs::libspdm_write_certificate_to_nvm}`
     = note: this error originates in the macro `libspdm_match_fn_prototypes` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `SPDM-Utils` (lib test) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

### CODE REVIEW

**Comment by alistair23** [comment]
Looks fine to me. You should be able to rebase it on https://github.com/westerndigitalcorporation/spdm-utils/pull/84 with just a small macro change

**Comment by twilfredo** [comment]
> able to rebase it on [#](https://github.com/westerndigitalcorporation/spdm-utils/pull/84)

We wouldn't want both of them though? Either this or #84 ?

**Comment by alistair23** [comment]
We can just convert https://github.com/westerndigitalcorporation/spdm-utils/pull/84 to use this approach.

https://github.com/westerndigitalcorporation/spdm-utils/pull/84 already updates all of the functions so it's probably worth just re-using that

**Comment by twilfredo** [comment]
> We can just convert #84 to use this approach.
> 
> #84 already updates all of the functions so it's probably worth just re-using that

Ah okay go it.

**Comment by twilfredo** [comment]
Continued in #91

**Pull request closed without merging**
